# Generated by Django 3.2.4 on 2021-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_kelompok_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelompok',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
